package seeds

import (
	"github.com/anidex/backend/internal/models"
)

// GetBadgeSeeds returns a comprehensive list of achievement badges
func GetBadgeSeeds() []models.Badge {
	return []models.Badge{
		// SPECIES COLLECTOR BADGES
		{
			Name:             "First Catch",
			Description:      "Congratulations on your very first animal catch! The journey of a thousand species begins with a single photograph.",
			ShortDesc:        "Catch your first animal",
			BadgeType:        models.BadgeTypeSpecies,
			BadgeRarity:      models.BadgeRarityBronze,
			IconURL:          "https://example.com/badges/first_catch.png",
			Color:            "#CD7F32",
			RequiredCount:    intPtr(1),
			PointsAwarded:    50,
			IsSecret:         false,
			IsActive:         true,
		},
		{
			Name:             "Big Cat Hunter",
			Description:      "You've successfully photographed 5 different big cat species! From house cats to mighty lions, you're becoming a feline photography expert.",
			ShortDesc:        "Catch 5 different big cats",
			BadgeType:        models.BadgeTypeSpecies,
			BadgeRarity:      models.BadgeRaritySilver,
			IconURL:          "https://example.com/badges/big_cat_hunter.png",
			Color:            "#C0C0C0",
			RequiredCount:    intPtr(5),
			RequiredSpecies:  []string{},
			PointsAwarded:    200,
			IsSecret:         false,
			IsActive:         true,
		},
		{
			Name:             "Bird Watcher",
			Description:      "You've spotted and photographed 25 different bird species! Your keen eye for avian photography is truly taking flight.",
			ShortDesc:        "Photograph 25 bird species",
			BadgeType:        models.BadgeTypeSpecies,
			BadgeRarity:      models.BadgeRarityGold,
			IconURL:          "https://example.com/badges/bird_watcher.png",
			Color:            "#FFD700",
			RequiredCount:    intPtr(25),
			RequiredSpecies:  []string{},
			PointsAwarded:    500,
			IsSecret:         false,
			IsActive:         true,
		},
		{
			Name:             "Marine Biologist",
			Description:      "You've documented 15 different marine species! Your underwater photography skills are making waves in the conservation community.",
			ShortDesc:        "Catch 15 marine animals",
			BadgeType:        models.BadgeTypeSpecies,
			BadgeRarity:      models.BadgeRarityGold,
			IconURL:          "https://example.com/badges/marine_biologist.png",
			Color:            "#FFD700",
			RequiredCount:    intPtr(15),
			RequiredSpecies:  []string{},
			PointsAwarded:    400,
			IsSecret:         false,
			IsActive:         true,
		},
		{
			Name:             "Century Club",
			Description:      "An incredible milestone! You've photographed 100 different animal species. You're now a certified wildlife photography expert!",
			ShortDesc:        "Catch 100 different species",
			BadgeType:        models.BadgeTypeCount,
			BadgeRarity:      models.BadgeRarityPlatinum,
			IconURL:          "https://example.com/badges/century_club.png",
			Color:            "#E5E4E2",
			RequiredCount:    intPtr(100),
			PointsAwarded:    1000,
			IsSecret:         false,
			IsActive:         true,
		},

		// RARITY BADGES
		{
			Name:             "Legendary Hunter",
			Description:      "You've achieved the impossible - photographing a legendary animal! These are the rarest creatures on Earth.",
			ShortDesc:        "Catch a legendary animal",
			BadgeType:        models.BadgeTypeRarity,
			BadgeRarity:      models.BadgeRarityDiamond,
			IconURL:          "https://example.com/badges/legendary_hunter.png",
			Color:            "#B9F2FF",
			RequiredRarity:   rarityPtr(models.RarityLegendary),
			RequiredCount:    intPtr(1),
			PointsAwarded:    2000,
			IsSecret:         true,
			IsActive:         true,
		},
		{
			Name:             "Epic Explorer",
			Description:      "You've encountered and photographed 5 epic animals! These rare sightings mark you as a true wildlife adventurer.",
			ShortDesc:        "Catch 5 epic animals",
			BadgeType:        models.BadgeTypeRarity,
			BadgeRarity:      models.BadgeRarityGold,
			IconURL:          "https://example.com/badges/epic_explorer.png",
			Color:            "#FFD700",
			RequiredRarity:   rarityPtr(models.RarityEpic),
			RequiredCount:    intPtr(5),
			PointsAwarded:    750,
			IsSecret:         false,
			IsActive:         true,
		},
		{
			Name:             "Rare Collector",
			Description:      "You've successfully photographed 10 rare animals! Your dedication to finding elusive species is paying off.",
			ShortDesc:        "Catch 10 rare animals",
			BadgeType:        models.BadgeTypeRarity,
			BadgeRarity:      models.BadgeRaritySilver,
			IconURL:          "https://example.com/badges/rare_collector.png",
			Color:            "#C0C0C0",
			RequiredRarity:   rarityPtr(models.RarityRare),
			RequiredCount:    intPtr(10),
			PointsAwarded:    300,
			IsSecret:         false,
			IsActive:         true,
		},

		// LOCATION BADGES
		{
			Name:             "Globe Trotter",
			Description:      "You've photographed animals in 10 different countries! Your passport to wildlife photography knows no borders.",
			ShortDesc:        "Catch animals in 10 countries",
			BadgeType:        models.BadgeTypeLocation,
			BadgeRarity:      models.BadgeRarityGold,
			IconURL:          "https://example.com/badges/globe_trotter.png",
			Color:            "#FFD700",
			RequiredCount:    intPtr(10),
			PointsAwarded:    600,
			IsSecret:         false,
			IsActive:         true,
		},
		{
			Name:             "Urban Wildlife Expert",
			Description:      "You've mastered the art of urban wildlife photography! 20 species caught in city environments.",
			ShortDesc:        "Catch 20 animals in urban areas",
			BadgeType:        models.BadgeTypeLocation,
			BadgeRarity:      models.BadgeRaritySilver,
			IconURL:          "https://example.com/badges/urban_wildlife.png",
			Color:            "#C0C0C0",
			RequiredLocationType: locationTypePtr(models.LocationUrban),
			RequiredCount:    intPtr(20),
			PointsAwarded:    250,
			IsSecret:         false,
			IsActive:         true,
		},
		{
			Name:             "Safari Master",
			Description:      "You've conquered the wilderness! 15 animals photographed in wild, untamed locations.",
			ShortDesc:        "Catch 15 animals in wilderness",
			BadgeType:        models.BadgeTypeLocation,
			BadgeRarity:      models.BadgeRarityGold,
			IconURL:          "https://example.com/badges/safari_master.png",
			Color:            "#FFD700",
			RequiredLocationType: locationTypePtr(models.LocationWilderness),
			RequiredCount:    intPtr(15),
			PointsAwarded:    500,
			IsSecret:         false,
			IsActive:         true,
		},
		{
			Name:             "Mountain Climber",
			Description:      "You've reached new heights in wildlife photography! 5 animals caught in mountain regions.",
			ShortDesc:        "Catch 5 animals in mountains",
			BadgeType:        models.BadgeTypeLocation,
			BadgeRarity:      models.BadgeRaritySilver,
			IconURL:          "https://example.com/badges/mountain_climber.png",
			Color:            "#C0C0C0",
			RequiredLocationType: locationTypePtr(models.LocationMountain),
			RequiredCount:    intPtr(5),
			PointsAwarded:    300,
			IsSecret:         false,
			IsActive:         true,
		},

		// STREAK BADGES
		{
			Name:             "Daily Dedication",
			Description:      "You've maintained a 7-day catching streak! Your daily commitment to wildlife photography is inspiring.",
			ShortDesc:        "Maintain a 7-day streak",
			BadgeType:        models.BadgeTypeStreak,
			BadgeRarity:      models.BadgeRarityBronze,
			IconURL:          "https://example.com/badges/daily_dedication.png",
			Color:            "#CD7F32",
			RequiredDays:     intPtr(7),
			PointsAwarded:    100,
			IsSecret:         false,
			IsActive:         true,
		},
		{
			Name:             "Monthly Master",
			Description:      "An incredible 30-day catching streak! You're showing legendary dedication to wildlife conservation.",
			ShortDesc:        "Maintain a 30-day streak",
			BadgeType:        models.BadgeTypeStreak,
			BadgeRarity:      models.BadgeRarityGold,
			IconURL:          "https://example.com/badges/monthly_master.png",
			Color:            "#FFD700",
			RequiredDays:     intPtr(30),
			PointsAwarded:    500,
			IsSecret:         false,
			IsActive:         true,
		},
		{
			Name:             "Eternal Explorer",
			Description:      "You've achieved the ultimate: a 100-day catching streak! You are a true wildlife photography legend.",
			ShortDesc:        "Maintain a 100-day streak",
			BadgeType:        models.BadgeTypeStreak,
			BadgeRarity:      models.BadgeRarityDiamond,
			IconURL:          "https://example.com/badges/eternal_explorer.png",
			Color:            "#B9F2FF",
			RequiredDays:     intPtr(100),
			PointsAwarded:    2000,
			IsSecret:         true,
			IsActive:         true,
		},

		// TIME-BASED BADGES
		{
			Name:             "Night Owl",
			Description:      "You've mastered nocturnal wildlife photography! 10 animals caught during nighttime hours.",
			ShortDesc:        "Catch 10 animals at night",
			BadgeType:        models.BadgeTypeTime,
			BadgeRarity:      models.BadgeRaritySilver,
			IconURL:          "https://example.com/badges/night_owl.png",
			Color:            "#C0C0C0",
			RequiredCount:    intPtr(10),
			PointsAwarded:    250,
			IsSecret:         false,
			IsActive:         true,
		},
		{
			Name:             "Early Bird",
			Description:      "The early bird catches the... animals! You've photographed 15 creatures during dawn hours.",
			ShortDesc:        "Catch 15 animals at dawn",
			BadgeType:        models.BadgeTypeTime,
			BadgeRarity:      models.BadgeRaritySilver,
			IconURL:          "https://example.com/badges/early_bird.png",
			Color:            "#C0C0C0",
			RequiredCount:    intPtr(15),
			PointsAwarded:    250,
			IsSecret:         false,
			IsActive:         true,
		},

		// CONSERVATION BADGES
		{
			Name:             "Conservation Hero",
			Description:      "You've photographed 10 endangered species, helping raise awareness for wildlife conservation!",
			ShortDesc:        "Catch 10 endangered species",
			BadgeType:        models.BadgeTypeConservation,
			BadgeRarity:      models.BadgeRarityPlatinum,
			IconURL:          "https://example.com/badges/conservation_hero.png",
			Color:            "#E5E4E2",
			RequiredCount:    intPtr(10),
			PointsAwarded:    800,
			IsSecret:         false,
			IsActive:         true,
		},
		{
			Name:             "Habitat Guardian",
			Description:      "You've documented wildlife in 5 different ecosystem types, supporting habitat preservation efforts!",
			ShortDesc:        "Catch animals in 5 ecosystems",
			BadgeType:        models.BadgeTypeConservation,
			BadgeRarity:      models.BadgeRarityGold,
			IconURL:          "https://example.com/badges/habitat_guardian.png",
			Color:            "#FFD700",
			RequiredCount:    intPtr(5),
			PointsAwarded:    400,
			IsSecret:         false,
			IsActive:         true,
		},

		// SOCIAL BADGES
		{
			Name:             "Community Leader",
			Description:      "Your photos have received 100 likes from the community! You're inspiring others to love wildlife.",
			ShortDesc:        "Receive 100 likes total",
			BadgeType:        models.BadgeTypeSocial,
			BadgeRarity:      models.BadgeRaritySilver,
			IconURL:          "https://example.com/badges/community_leader.png",
			Color:            "#C0C0C0",
			RequiredCount:    intPtr(100),
			PointsAwarded:    200,
			IsSecret:         false,
			IsActive:         true,
		},
		{
			Name:             "Photo Artist",
			Description:      "You've shared 50 public photos with the community! Your artistic eye is helping others discover wildlife.",
			ShortDesc:        "Share 50 public photos",
			BadgeType:        models.BadgeTypeSocial,
			BadgeRarity:      models.BadgeRaritySilver,
			IconURL:          "https://example.com/badges/photo_artist.png",
			Color:            "#C0C0C0",
			RequiredCount:    intPtr(50),
			PointsAwarded:    250,
			IsSecret:         false,
			IsActive:         true,
		},
		{
			Name:             "Mentor",
			Description:      "You've helped verify 25 catches for other users! Your expertise is valuable to the community.",
			ShortDesc:        "Verify 25 catches for others",
			BadgeType:        models.BadgeTypeSocial,
			BadgeRarity:      models.BadgeRarityGold,
			IconURL:          "https://example.com/badges/mentor.png",
			Color:            "#FFD700",
			RequiredCount:    intPtr(25),
			PointsAwarded:    500,
			IsSecret:         false,
			IsActive:         true,
		},

		// SPECIAL ACHIEVEMENT BADGES
		{
			Name:             "Weather Warrior",
			Description:      "You've braved all weather conditions! Caught animals in 5 different weather types.",
			ShortDesc:        "Catch animals in 5 weather types",
			BadgeType:        models.BadgeTypeSpecial,
			BadgeRarity:      models.BadgeRaritySilver,
			IconURL:          "https://example.com/badges/weather_warrior.png",
			Color:            "#C0C0C0",
			RequiredCount:    intPtr(5),
			PointsAwarded:    200,
			IsSecret:         false,
			IsActive:         true,
		},
		{
			Name:             "Seasonal Specialist",
			Description:      "You've documented the changing seasons! Animals caught during all four seasons of the year.",
			ShortDesc:        "Catch animals in all seasons",
			BadgeType:        models.BadgeTypeSeasonal,
			BadgeRarity:      models.BadgeRarityGold,
			IconURL:          "https://example.com/badges/seasonal_specialist.png",
			Color:            "#FFD700",
			RequiredCount:    intPtr(4),
			PointsAwarded:    300,
			IsSecret:         false,
			IsActive:         true,
		},
		{
			Name:             "The Completionist",
			Description:      "You've achieved the impossible - caught every species in the database! You are a true AniDex master!",
			ShortDesc:        "Catch every available species",
			BadgeType:        models.BadgeTypeSpecial,
			BadgeRarity:      models.BadgeRarityDiamond,
			IconURL:          "https://example.com/badges/completionist.png",
			Color:            "#B9F2FF",
			RequiredCount:    intPtr(500), // Will be updated based on total species
			PointsAwarded:    5000,
			IsSecret:         true,
			IsActive:         true,
		},

		// HIDDEN/SECRET BADGES
		{
			Name:             "Lucky Shot",
			Description:      "You caught a legendary animal on your very first try! Sometimes the wildlife gods smile upon us.",
			ShortDesc:        "Catch legendary on first attempt",
			BadgeType:        models.BadgeTypeSpecial,
			BadgeRarity:      models.BadgeRarityDiamond,
			IconURL:          "https://example.com/badges/lucky_shot.png",
			Color:            "#B9F2FF",
			RequiredCount:    intPtr(1),
			PointsAwarded:    1000,
			IsSecret:         true,
			IsActive:         true,
		},
		{
			Name:             "Midnight Photographer",
			Description:      "You've mastered the art of midnight photography! This secret badge is for the truly dedicated.",
			ShortDesc:        "Take photo at exactly midnight",
			BadgeType:        models.BadgeTypeSpecial,
			BadgeRarity:      models.BadgeRarityPlatinum,
			IconURL:          "https://example.com/badges/midnight_photographer.png",
			Color:            "#E5E4E2",
			RequiredCount:    intPtr(1),
			PointsAwarded:    500,
			IsSecret:         true,
			IsActive:         true,
		},
	}
}

// Helper functions for pointer values
func rarityPtr(r models.Rarity) *models.Rarity {
	return &r
}

func locationTypePtr(lt models.LocationType) *models.LocationType {
	return &lt
}
