package seeds

import (
	"github.com/anidex/backend/internal/models"
)

// GetLocationSeeds returns a slice of famous wildlife locations for seeding
func GetLocationSeeds() []models.Location {
	return []models.Location{
		// AFRICAN SAFARI LOCATIONS
		{
			Latitude:        -2.1540,
			Longitude:       34.6857,
			Altitude:        floatPtr(1500.0),
			Address:         "Serengeti National Park, Tanzania",
			City:            "Arusha",
			State:           "Arusha Region",
			Country:         "Tanzania",
			CountryCode:     "TZ",
			Name:            "Serengeti National Park",
			Description:     "Famous for the annual Great Migration of wildebeest and zebras. Home to the Big Five and diverse wildlife.",
			LocationType:    models.LocationWilderness,
			Ecosystem:       "Savanna grasslands",
			Climate:         "Tropical savanna",
			Habitat:         "Open grasslands with scattered trees",
			CatchCount:      1250,
			SpeciesCount:    89,
			UserCount:       342,
			SafetyRating:    intPtr(4),
			Accessibility:   "moderate",
			IsPublic:        true,
			RequiresPermit:  true,
		},
		{
			Latitude:        -24.7963,
			Longitude:       31.5540,
			Altitude:        floatPtr(300.0),
			Address:         "Kruger National Park, South Africa",
			City:            "Skukuza",
			State:           "Mpumalanga",
			Country:         "South Africa",
			CountryCode:     "ZA",
			Name:            "Kruger National Park",
			Description:     "One of Africa's largest game reserves, known for Big Five safari experiences.",
			LocationType:    models.LocationWilderness,
			Ecosystem:       "Savanna",
			Climate:         "Subtropical",
			Habitat:         "Mixed bushveld and grasslands",
			CatchCount:      2100,
			SpeciesCount:    156,
			UserCount:       567,
			SafetyRating:    intPtr(5),
			Accessibility:   "easy",
			IsPublic:        true,
			RequiresPermit:  true,
		},

		// NORTH AMERICAN WILDERNESS
		{
			Latitude:        44.4280,
			Longitude:       -110.5885,
			Altitude:        floatPtr(2400.0),
			Address:         "Yellowstone National Park, Wyoming, USA",
			City:            "Yellowstone",
			State:           "Wyoming",
			Country:         "United States",
			CountryCode:     "US",
			Name:            "Yellowstone National Park",
			Description:     "America's first national park, home to bison, wolves, bears, and geothermal features.",
			LocationType:    models.LocationWilderness,
			Ecosystem:       "Temperate grassland and forest",
			Climate:         "Continental",
			Habitat:         "Forests, grasslands, mountains",
			CatchCount:      1800,
			SpeciesCount:    67,
			UserCount:       890,
			SafetyRating:    intPtr(4),
			Accessibility:   "moderate",
			IsPublic:        true,
			RequiresPermit:  false,
		},
		{
			Latitude:        64.0685,
			Longitude:       -152.2782,
			Altitude:        floatPtr(200.0),
			Address:         "Denali National Park, Alaska, USA",
			City:            "Denali",
			State:           "Alaska",
			Country:         "United States",
			CountryCode:     "US",
			Name:            "Denali National Park",
			Description:     "Home to North America's tallest peak and diverse Arctic wildlife including grizzly bears and caribou.",
			LocationType:    models.LocationWilderness,
			Ecosystem:       "Tundra and boreal forest",
			Climate:         "Subarctic",
			Habitat:         "Tundra, taiga forests",
			CatchCount:      650,
			SpeciesCount:    42,
			UserCount:       234,
			SafetyRating:    intPtr(3),
			Accessibility:   "difficult",
			IsPublic:        true,
			RequiresPermit:  true,
		},

		// ASIAN WILDLIFE DESTINATIONS
		{
			Latitude:        27.7000,
			Longitude:       85.3333,
			Altitude:        floatPtr(3500.0),
			Address:         "Sagarmatha National Park, Nepal",
			City:            "Namche Bazaar",
			State:           "Province No. 1",
			Country:         "Nepal",
			CountryCode:     "NP",
			Name:            "Sagarmatha National Park",
			Description:     "Home to Mount Everest and rare high-altitude wildlife including snow leopards and red pandas.",
			LocationType:    models.LocationMountain,
			Ecosystem:       "Alpine",
			Climate:         "Alpine",
			Habitat:         "High-altitude forests and meadows",
			CatchCount:      145,
			SpeciesCount:    28,
			UserCount:       67,
			SafetyRating:    intPtr(2),
			Accessibility:   "difficult",
			IsPublic:        true,
			RequiresPermit:  true,
		},
		{
			Latitude:        12.5266,
			Longitude:       75.7219,
			Altitude:        floatPtr(800.0),
			Address:         "Nagarhole National Park, Karnataka, India",
			City:            "Mysore",
			State:           "Karnataka",
			Country:         "India",
			CountryCode:     "IN",
			Name:            "Nagarhole National Park",
			Description:     "Part of the Nilgiri Biosphere Reserve, famous for tigers, elephants, and diverse bird life.",
			LocationType:    models.LocationWilderness,
			Ecosystem:       "Tropical deciduous forest",
			Climate:         "Tropical",
			Habitat:         "Dense forests and grasslands",
			CatchCount:      890,
			SpeciesCount:    78,
			UserCount:       189,
			SafetyRating:    intPtr(4),
			Accessibility:   "moderate",
			IsPublic:        true,
			RequiresPermit:  true,
		},

		// SOUTH AMERICAN RAINFORESTS
		{
			Latitude:        -3.4653,
			Longitude:       -62.2159,
			Altitude:        floatPtr(100.0),
			Address:         "Amazon Rainforest, Brazil",
			City:            "Manaus",
			State:           "Amazonas",
			Country:         "Brazil",
			CountryCode:     "BR",
			Name:            "Amazon Rainforest",
			Description:     "The world's largest tropical rainforest, home to incredible biodiversity.",
			LocationType:    models.LocationForest,
			Ecosystem:       "Tropical rainforest",
			Climate:         "Tropical",
			Habitat:         "Dense rainforest canopy",
			CatchCount:      2500,
			SpeciesCount:    234,
			UserCount:       456,
			SafetyRating:    intPtr(3),
			Accessibility:   "difficult",
			IsPublic:        true,
			RequiresPermit:  true,
		},

		// OCEANIA UNIQUE ECOSYSTEMS
		{
			Latitude:        -25.3444,
			Longitude:       131.0369,
			Altitude:        floatPtr(348.0),
			Address:         "Uluru-Kata Tjuta National Park, Australia",
			City:            "Yulara",
			State:           "Northern Territory",
			Country:         "Australia",
			CountryCode:     "AU",
			Name:            "Uluru-Kata Tjuta National Park",
			Description:     "Sacred Aboriginal land featuring unique desert wildlife and iconic rock formations.",
			LocationType:    models.LocationDesert,
			Ecosystem:       "Arid desert",
			Climate:         "Arid",
			Habitat:         "Red sand desert with sparse vegetation",
			CatchCount:      320,
			SpeciesCount:    45,
			UserCount:       123,
			SafetyRating:    intPtr(4),
			Accessibility:   "easy",
			IsPublic:        true,
			RequiresPermit:  false,
		},

		// EUROPEAN WILDLIFE AREAS
		{
			Latitude:        46.8003,
			Longitude:       10.3000,
			Altitude:        floatPtr(1500.0),
			Address:         "Swiss National Park, Switzerland",
			City:            "Zernez",
			State:           "Grisons",
			Country:         "Switzerland",
			CountryCode:     "CH",
			Name:            "Swiss National Park",
			Description:     "Alpine wildlife sanctuary with ibex, marmots, and golden eagles.",
			LocationType:    models.LocationMountain,
			Ecosystem:       "Alpine",
			Climate:         "Alpine",
			Habitat:         "Mountain forests and alpine meadows",
			CatchCount:      450,
			SpeciesCount:    38,
			UserCount:       167,
			SafetyRating:    intPtr(5),
			Accessibility:   "moderate",
			IsPublic:        true,
			RequiresPermit:  false,
		},

		// MARINE LOCATIONS
		{
			Latitude:        21.3099,
			Longitude:       -157.8581,
			Altitude:        floatPtr(0.0),
			Address:         "Hanauma Bay, Hawaii, USA",
			City:            "Honolulu",
			State:           "Hawaii",
			Country:         "United States",
			CountryCode:     "US",
			Name:            "Hanauma Bay Nature Preserve",
			Description:     "Protected marine ecosystem famous for snorkeling and tropical fish observation.",
			LocationType:    models.LocationOcean,
			Ecosystem:       "Coral reef",
			Climate:         "Tropical",
			Habitat:         "Coral reef and clear waters",
			CatchCount:      1200,
			SpeciesCount:    89,
			UserCount:       678,
			SafetyRating:    intPtr(5),
			Accessibility:   "easy",
			IsPublic:        true,
			RequiresPermit:  false,
		},

		// URBAN WILDLIFE AREAS
		{
			Latitude:        40.7829,
			Longitude:       -73.9654,
			Altitude:        floatPtr(40.0),
			Address:         "Central Park, New York, NY, USA",
			City:            "New York",
			State:           "New York",
			Country:         "United States",
			CountryCode:     "US",
			Name:            "Central Park",
			Description:     "Urban oasis in Manhattan with diverse bird life and small mammals.",
			LocationType:    models.LocationUrban,
			Ecosystem:       "Urban park",
			Climate:         "Temperate",
			Habitat:         "Mixed urban parkland",
			CatchCount:      890,
			SpeciesCount:    56,
			UserCount:       1234,
			SafetyRating:    intPtr(5),
			Accessibility:   "easy",
			IsPublic:        true,
			RequiresPermit:  false,
		},
		{
			Latitude:        51.5074,
			Longitude:       -0.1278,
			Altitude:        floatPtr(11.0),
			Address:         "Hyde Park, London, England",
			City:            "London",
			State:           "England",
			Country:         "United Kingdom",
			CountryCode:     "GB",
			Name:            "Hyde Park",
			Description:     "Historic London park with waterfowl, squirrels, and urban bird species.",
			LocationType:    models.LocationUrban,
			Ecosystem:       "Urban park",
			Climate:         "Temperate oceanic",
			Habitat:         "Parkland with lakes and gardens",
			CatchCount:      567,
			SpeciesCount:    34,
			UserCount:       789,
			SafetyRating:    intPtr(5),
			Accessibility:   "easy",
			IsPublic:        true,
			RequiresPermit:  false,
		},

		// ZOOS AND SANCTUARIES
		{
			Latitude:        38.9517,
			Longitude:       -77.0492,
			Altitude:        floatPtr(100.0),
			Address:         "Smithsonian National Zoo, Washington, DC, USA",
			City:            "Washington",
			State:           "District of Columbia",
			Country:         "United States",
			CountryCode:     "US",
			Name:            "Smithsonian National Zoo",
			Description:     "World-renowned zoo famous for giant pandas and conservation programs.",
			LocationType:    models.LocationZoo,
			Ecosystem:       "Captive wildlife",
			Climate:         "Temperate",
			Habitat:         "Designed animal habitats",
			CatchCount:      2800,
			SpeciesCount:    145,
			UserCount:       1567,
			SafetyRating:    intPtr(5),
			Accessibility:   "easy",
			IsPublic:        true,
			RequiresPermit:  false,
		},
		{
			Latitude:        -1.2921,
			Longitude:       36.8219,
			Altitude:        floatPtr(1795.0),
			Address:         "David Sheldrick Wildlife Trust, Nairobi, Kenya",
			City:            "Nairobi",
			State:           "Nairobi County",
			Country:         "Kenya",
			CountryCode:     "KE",
			Name:            "David Sheldrick Wildlife Trust",
			Description:     "Elephant orphanage and wildlife sanctuary dedicated to conservation.",
			LocationType:    models.LocationSanctuary,
			Ecosystem:       "Sanctuary",
			Climate:         "Tropical highland",
			Habitat:         "Protected wildlife sanctuary",
			CatchCount:      450,
			SpeciesCount:    23,
			UserCount:       234,
			SafetyRating:    intPtr(4),
			Accessibility:   "easy",
			IsPublic:        true,
			RequiresPermit:  false,
		},
	}
}

// GetHotspotSeeds returns popular hotspot locations
func GetHotspotSeeds() []models.Hotspot {
	return []models.Hotspot{
		{
			Name:            "Big Five Safari Experience",
			Description:     "Ultimate African safari experience to spot lions, leopards, rhinos, elephants, and buffalo.",
			BestTimeToVisit: "June to October (dry season)",
			PeakSeason:      "July-September",
			PopularityScore: 95,
			WeeklyCatches:   450,
			MonthlyCatches:  1800,
			TopSpecies:      []string{},
			HasParking:      true,
			HasRestrooms:    true,
			HasFood:         true,
			HasGuides:       true,
			EntryFee:        floatPtr(75.0),
			IsVerified:      true,
			IsActive:        true,
		},
		{
			Name:            "Central Park Birding",
			Description:     "Premier urban birding location with over 200 species recorded throughout the year.",
			BestTimeToVisit: "Spring and fall migration (April-May, September-October)",
			PeakSeason:      "April-May",
			PopularityScore: 88,
			WeeklyCatches:   230,
			MonthlyCatches:  920,
			TopSpecies:      []string{},
			HasParking:      false,
			HasRestrooms:    true,
			HasFood:         true,
			HasGuides:       false,
			EntryFee:        floatPtr(0.0),
			IsVerified:      true,
			IsActive:        true,
		},
		{
			Name:            "Amazon Wildlife Lodge",
			Description:     "Deep rainforest location with incredible biodiversity and rare species sightings.",
			BestTimeToVisit: "Dry season (June to November)",
			PeakSeason:      "July-September",
			PopularityScore: 92,
			WeeklyCatches:   180,
			MonthlyCatches:  720,
			TopSpecies:      []string{},
			HasParking:      false,
			HasRestrooms:    true,
			HasFood:         true,
			HasGuides:       true,
			EntryFee:        floatPtr(120.0),
			IsVerified:      true,
			IsActive:        true,
		},
		{
			Name:            "Yellowstone Wildlife Corridor",
			Description:     "Famous wildlife watching area with wolves, bears, bison, and elk.",
			BestTimeToVisit: "May to September",
			PeakSeason:      "June-August",
			PopularityScore: 90,
			WeeklyCatches:   320,
			MonthlyCatches:  1280,
			TopSpecies:      []string{},
			HasParking:      true,
			HasRestrooms:    true,
			HasFood:         true,
			HasGuides:       true,
			EntryFee:        floatPtr(35.0),
			IsVerified:      true,
			IsActive:        true,
		},
	}
}
