package seeds

import (
	"github.com/anidex/backend/internal/models"
)

// GetSpeciesSeeds returns a slice of species for seeding the database
func GetSpeciesSeeds() []models.Species {
	return []models.Species{
		// LEGENDARY ANIMALS (Extremely Rare)
		{
			CommonName:         "Snow Leopard",
			ScientificName:     "Panthera uncia",
			Category:           models.CategoryMammal,
			Family:             "Felidae",
			Genus:              "Panthera",
			Description:        "A large cat native to the mountain ranges of Central and South Asia. Known for its beautiful thick fur and incredible jumping ability.",
			AverageWeight:      floatPtr(35.0),
			AverageLength:      floatPtr(120.0),
			AverageLifespan:    intPtr(15),
			Habitat:            "High mountain slopes and rocky areas",
			Diet:               "Carnivore",
			Behavior:           "Solitary, territorial, excellent climber",
			GeographicRange:    "Central and South Asia mountains",
			ConservationStatus: models.StatusVulnerable,
			Rarity:             models.RarityLegendary,
			BasePoints:         200,
			DifficultyLevel:    10,
			DefaultImageURL:    "https://example.com/images/snow_leopard.jpg",
			WikipediaURL:       "https://en.wikipedia.org/wiki/Snow_leopard",
			IsActive:           true,
		},
		{
			CommonName:         "Giant Panda",
			ScientificName:     "Ailuropoda melanoleuca",
			Category:           models.CategoryMammal,
			Family:             "Ursidae",
			Genus:              "Ailuropoda",
			Description:        "A bear species endemic to China, known for its distinctive black and white coloring and bamboo diet.",
			AverageWeight:      floatPtr(100.0),
			AverageLength:      floatPtr(150.0),
			AverageLifespan:    intPtr(20),
			Habitat:            "Bamboo forests in mountains",
			Diet:               "Herbivore (99% bamboo)",
			Behavior:           "Solitary, peaceful, excellent climber",
			GeographicRange:    "Central China",
			ConservationStatus: models.StatusVulnerable,
			Rarity:             models.RarityLegendary,
			BasePoints:         180,
			DifficultyLevel:    9,
			DefaultImageURL:    "https://example.com/images/giant_panda.jpg",
			WikipediaURL:       "https://en.wikipedia.org/wiki/Giant_panda",
			IsActive:           true,
		},
		{
			CommonName:         "Siberian Tiger",
			ScientificName:     "Panthera tigris tigris",
			Category:           models.CategoryMammal,
			Family:             "Felidae",
			Genus:              "Panthera",
			Description:        "The largest living cat subspecies, native to eastern Russia and parts of China.",
			AverageWeight:      floatPtr(200.0),
			AverageLength:      floatPtr(280.0),
			AverageLifespan:    intPtr(16),
			Habitat:            "Boreal forests and grasslands",
			Diet:               "Carnivore",
			Behavior:           "Solitary, territorial, excellent swimmer",
			GeographicRange:    "Eastern Russia, Northeast China",
			ConservationStatus: models.StatusEndangered,
			Rarity:             models.RarityLegendary,
			BasePoints:         220,
			DifficultyLevel:    10,
			DefaultImageURL:    "https://example.com/images/siberian_tiger.jpg",
			WikipediaURL:       "https://en.wikipedia.org/wiki/Siberian_tiger",
			IsActive:           true,
		},

		// EPIC ANIMALS (Very Rare)
		{
			CommonName:         "African Elephant",
			ScientificName:     "Loxodonta africana",
			Category:           models.CategoryMammal,
			Family:             "Elephantidae",
			Genus:              "Loxodonta",
			Description:        "The largest living terrestrial animal, known for intelligence, memory, and complex social behavior.",
			AverageWeight:      floatPtr(6000.0),
			AverageLength:      floatPtr(650.0),
			AverageLifespan:    intPtr(70),
			Habitat:            "Savannas, forests, deserts",
			Diet:               "Herbivore",
			Behavior:           "Highly social, matriarchal herds",
			GeographicRange:    "Sub-Saharan Africa",
			ConservationStatus: models.StatusEndangered,
			Rarity:             models.RarityEpic,
			BasePoints:         150,
			DifficultyLevel:    8,
			DefaultImageURL:    "https://example.com/images/african_elephant.jpg",
			WikipediaURL:       "https://en.wikipedia.org/wiki/African_elephant",
			IsActive:           true,
		},
		{
			CommonName:         "Bald Eagle",
			ScientificName:     "Haliaeetus leucocephalus",
			Category:           models.CategoryBird,
			Family:             "Accipitridae",
			Genus:              "Haliaeetus",
			Description:        "A bird of prey found in North America, known as the national bird of the United States.",
			AverageWeight:      floatPtr(6.0),
			AverageLength:      floatPtr(100.0),
			AverageLifespan:    intPtr(30),
			Habitat:            "Near large bodies of water with abundant fish",
			Diet:               "Carnivore (mainly fish)",
			Behavior:           "Monogamous pairs, excellent eyesight",
			GeographicRange:    "North America",
			ConservationStatus: models.StatusLeastConcern,
			Rarity:             models.RarityEpic,
			BasePoints:         120,
			DifficultyLevel:    7,
			DefaultImageURL:    "https://example.com/images/bald_eagle.jpg",
			WikipediaURL:       "https://en.wikipedia.org/wiki/Bald_eagle",
			IsActive:           true,
		},
		{
			CommonName:         "Mountain Gorilla",
			ScientificName:     "Gorilla beringei beringei",
			Category:           models.CategoryMammal,
			Family:             "Hominidae",
			Genus:              "Gorilla",
			Description:        "A subspecies of eastern gorilla found in the volcanic mountains of central Africa.",
			AverageWeight:      floatPtr(180.0),
			AverageLength:      floatPtr(150.0),
			AverageLifespan:    intPtr(40),
			Habitat:            "Mountain forests",
			Diet:               "Herbivore",
			Behavior:           "Social groups led by silverback male",
			GeographicRange:    "Rwanda, Uganda, Democratic Republic of Congo",
			ConservationStatus: models.StatusCriticallyEndangered,
			Rarity:             models.RarityEpic,
			BasePoints:         160,
			DifficultyLevel:    9,
			DefaultImageURL:    "https://example.com/images/mountain_gorilla.jpg",
			WikipediaURL:       "https://en.wikipedia.org/wiki/Mountain_gorilla",
			IsActive:           true,
		},

		// RARE ANIMALS (Hard to Find)
		{
			CommonName:         "Red Fox",
			ScientificName:     "Vulpes vulpes",
			Category:           models.CategoryMammal,
			Family:             "Canidae",
			Genus:              "Vulpes",
			Description:        "The largest of the true foxes, known for intelligence and adaptability.",
			AverageWeight:      floatPtr(7.0),
			AverageLength:      floatPtr(70.0),
			AverageLifespan:    intPtr(5),
			Habitat:            "Forests, grasslands, mountains, deserts",
			Diet:               "Omnivore",
			Behavior:           "Mostly solitary, very adaptable",
			GeographicRange:    "Northern Hemisphere",
			ConservationStatus: models.StatusLeastConcern,
			Rarity:             models.RarityRare,
			BasePoints:         80,
			DifficultyLevel:    6,
			DefaultImageURL:    "https://example.com/images/red_fox.jpg",
			WikipediaURL:       "https://en.wikipedia.org/wiki/Red_fox",
			IsActive:           true,
		},
		{
			CommonName:         "Great Horned Owl",
			ScientificName:     "Bubo virginianus",
			Category:           models.CategoryBird,
			Family:             "Strigidae",
			Genus:              "Bubo",
			Description:        "A large owl native to the Americas, known for its distinctive horn-like ear tufts.",
			AverageWeight:      floatPtr(1.4),
			AverageLength:      floatPtr(55.0),
			AverageLifespan:    intPtr(13),
			Habitat:            "Varied: forests, wetlands, parks, cities",
			Diet:               "Carnivore",
			Behavior:           "Nocturnal, territorial, powerful hunter",
			GeographicRange:    "Americas",
			ConservationStatus: models.StatusLeastConcern,
			Rarity:             models.RarityRare,
			BasePoints:         70,
			DifficultyLevel:    5,
			DefaultImageURL:    "https://example.com/images/great_horned_owl.jpg",
			WikipediaURL:       "https://en.wikipedia.org/wiki/Great_horned_owl",
			IsActive:           true,
		},
		{
			CommonName:         "Green Sea Turtle",
			ScientificName:     "Chelonia mydas",
			Category:           models.CategoryReptile,
			Family:             "Cheloniidae",
			Genus:              "Chelonia",
			Description:        "A large sea turtle distributed throughout tropical and subtropical seas.",
			AverageWeight:      floatPtr(150.0),
			AverageLength:      floatPtr(120.0),
			AverageLifespan:    intPtr(80),
			Habitat:            "Coastal waters, coral reefs, seagrass beds",
			Diet:               "Herbivore (as adults)",
			Behavior:           "Migratory, long-distance travelers",
			GeographicRange:    "Tropical and subtropical oceans worldwide",
			ConservationStatus: models.StatusEndangered,
			Rarity:             models.RarityRare,
			BasePoints:         90,
			DifficultyLevel:    7,
			DefaultImageURL:    "https://example.com/images/green_sea_turtle.jpg",
			WikipediaURL:       "https://en.wikipedia.org/wiki/Green_sea_turtle",
			IsActive:           true,
		},

		// UNCOMMON ANIMALS (Moderate Difficulty)
		{
			CommonName:         "White-tailed Deer",
			ScientificName:     "Odocoileus virginianus",
			Category:           models.CategoryMammal,
			Family:             "Cervidae",
			Genus:              "Odocoileus",
			Description:        "A medium-sized deer native to North, Central and South America.",
			AverageWeight:      floatPtr(68.0),
			AverageLength:      floatPtr(170.0),
			AverageLifespan:    intPtr(6),
			Habitat:            "Forests, farmlands, brushlands",
			Diet:               "Herbivore",
			Behavior:           "Social in winter, territorial in summer",
			GeographicRange:    "Americas",
			ConservationStatus: models.StatusLeastConcern,
			Rarity:             models.RarityUncommon,
			BasePoints:         40,
			DifficultyLevel:    4,
			DefaultImageURL:    "https://example.com/images/white_tailed_deer.jpg",
			WikipediaURL:       "https://en.wikipedia.org/wiki/White-tailed_deer",
			IsActive:           true,
		},
		{
			CommonName:         "Northern Cardinal",
			ScientificName:     "Cardinalis cardinalis",
			Category:           models.CategoryBird,
			Family:             "Cardinalidae",
			Genus:              "Cardinalis",
			Description:        "A North American bird known for the male's bright red coloring.",
			AverageWeight:      floatPtr(0.045),
			AverageLength:      floatPtr(23.0),
			AverageLifespan:    intPtr(3),
			Habitat:            "Woodlands, gardens, shrublands",
			Diet:               "Omnivore (seeds, insects, fruits)",
			Behavior:           "Non-migratory, territorial",
			GeographicRange:    "Eastern North America",
			ConservationStatus: models.StatusLeastConcern,
			Rarity:             models.RarityUncommon,
			BasePoints:         30,
			DifficultyLevel:    3,
			DefaultImageURL:    "https://example.com/images/northern_cardinal.jpg",
			WikipediaURL:       "https://en.wikipedia.org/wiki/Northern_cardinal",
			IsActive:           true,
		},
		{
			CommonName:         "Monarch Butterfly",
			ScientificName:     "Danaus plexippus",
			Category:           models.CategoryInsect,
			Family:             "Nymphalidae",
			Genus:              "Danaus",
			Description:        "A milkweed butterfly known for its incredible migration patterns.",
			AverageWeight:      floatPtr(0.0005),
			AverageLength:      floatPtr(10.0),
			AverageLifespan:    intPtr(1),
			Habitat:            "Open areas, meadows, gardens",
			Diet:               "Herbivore (nectar)",
			Behavior:           "Migratory, toxic to predators",
			GeographicRange:    "North and South America",
			ConservationStatus: models.StatusNearThreatened,
			Rarity:             models.RarityUncommon,
			BasePoints:         35,
			DifficultyLevel:    3,
			DefaultImageURL:    "https://example.com/images/monarch_butterfly.jpg",
			WikipediaURL:       "https://en.wikipedia.org/wiki/Monarch_butterfly",
			IsActive:           true,
		},

		// COMMON ANIMALS (Easy to Find)
		{
			CommonName:         "Eastern Gray Squirrel",
			ScientificName:     "Sciurus carolinensis",
			Category:           models.CategoryMammal,
			Family:             "Sciuridae",
			Genus:              "Sciurus",
			Description:        "A tree squirrel native to eastern North America, common in urban areas.",
			AverageWeight:      floatPtr(0.5),
			AverageLength:      floatPtr(25.0),
			AverageLifespan:    intPtr(6),
			Habitat:            "Hardwood and mixed forests, urban parks",
			Diet:               "Omnivore (nuts, seeds, insects)",
			Behavior:           "Agile climber, food hoarder",
			GeographicRange:    "Eastern North America",
			ConservationStatus: models.StatusLeastConcern,
			Rarity:             models.RarityCommon,
			BasePoints:         15,
			DifficultyLevel:    1,
			DefaultImageURL:    "https://example.com/images/gray_squirrel.jpg",
			WikipediaURL:       "https://en.wikipedia.org/wiki/Eastern_gray_squirrel",
			IsActive:           true,
		},
		{
			CommonName:         "American Robin",
			ScientificName:     "Turdus migratorius",
			Category:           models.CategoryBird,
			Family:             "Turdidae",
			Genus:              "Turdus",
			Description:        "A migratory songbird and the state bird of Connecticut, Michigan, and Wisconsin.",
			AverageWeight:      floatPtr(0.077),
			AverageLength:      floatPtr(25.0),
			AverageLifespan:    intPtr(2),
			Habitat:            "Gardens, parks, lawns, forests",
			Diet:               "Omnivore (worms, insects, fruits)",
			Behavior:           "Ground forager, melodic singer",
			GeographicRange:    "North America",
			ConservationStatus: models.StatusLeastConcern,
			Rarity:             models.RarityCommon,
			BasePoints:         10,
			DifficultyLevel:    1,
			DefaultImageURL:    "https://example.com/images/american_robin.jpg",
			WikipediaURL:       "https://en.wikipedia.org/wiki/American_robin",
			IsActive:           true,
		},
		{
			CommonName:         "Domestic Cat",
			ScientificName:     "Felis catus",
			Category:           models.CategoryMammal,
			Family:             "Felidae",
			Genus:              "Felis",
			Description:        "A small carnivorous mammal, commonly kept as a house pet.",
			AverageWeight:      floatPtr(4.5),
			AverageLength:      floatPtr(46.0),
			AverageLifespan:    intPtr(15),
			Habitat:            "Urban and rural environments worldwide",
			Diet:               "Carnivore",
			Behavior:           "Independent, territorial, social with humans",
			GeographicRange:    "Worldwide",
			ConservationStatus: models.StatusLeastConcern,
			Rarity:             models.RarityCommon,
			BasePoints:         5,
			DifficultyLevel:    1,
			DefaultImageURL:    "https://example.com/images/domestic_cat.jpg",
			WikipediaURL:       "https://en.wikipedia.org/wiki/Cat",
			IsActive:           true,
		},
		{
			CommonName:         "Rock Pigeon",
			ScientificName:     "Columba livia",
			Category:           models.CategoryBird,
			Family:             "Columbidae",
			Genus:              "Columba",
			Description:        "A common urban bird, originally from Europe, North Africa, and South Asia.",
			AverageWeight:      floatPtr(0.35),
			AverageLength:      floatPtr(32.0),
			AverageLifespan:    intPtr(6),
			Habitat:            "Cities, towns, agricultural areas",
			Diet:               "Omnivore (seeds, fruits, insects)",
			Behavior:           "Highly social, excellent navigators",
			GeographicRange:    "Worldwide (introduced)",
			ConservationStatus: models.StatusLeastConcern,
			Rarity:             models.RarityCommon,
			BasePoints:         8,
			DifficultyLevel:    1,
			DefaultImageURL:    "https://example.com/images/rock_pigeon.jpg",
			WikipediaURL:       "https://en.wikipedia.org/wiki/Rock_dove",
			IsActive:           true,
		},
	}
}

// Helper functions for pointer values
func floatPtr(f float64) *float64 {
	return &f
}

func intPtr(i int) *int {
	return &i
}
