# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '13.4'
prepare_react_native_project!

# use_modular_headers!
use_frameworks! :linkage => :static

target 'Anidex' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    # Fix for Xcode 16+ compatibility issues and add Photos framework
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
        config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
        config.build_settings['SWIFT_DISABLE_SAFETY_CHECKS'] = 'YES'
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        
        # Only disable modules for React Native targets, keep them enabled for Firebase
        if target.name.start_with?('React') || target.name.include?('RN') || target.name.include?('Yoga') || target.name.include?('boost') || target.name.include?('DoubleConversion') || target.name.include?('glog') || target.name.include?('fmt')
          config.build_settings['CLANG_ENABLE_MODULES'] = 'NO'
        else
          config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
        end
      end
    end
  end
end
